### ISSUE TITLE
Administrador: ver cantidad de favoritos de un repositorio

### ISSUE THREAD

**Issue by soriac** [soriac/tacs-no-se-cae-mas#12]

**Comment by soriac** [comment]
Opino que debería ser la misma ruta que cuando un usuario busca un repositorio (#6).

Esa ruta debería darse cuenta por contexto si el usuario es común o admin, y si es admin agregar ese dato.

**Comment by thehighestprimenumber** [comment]
pensé lo mismo!

**Comment by lucascharlab** [comment]
si, opino exactamente igual! que devuelva toda la info junta si es admin

**Comment by thehighestprimenumber** [comment]
@lucascharlab esto se hizo como prate del #6
