### ISSUE TITLE
Usuario: buscar y filtrar repositorios

### ISSUE THREAD

**Issue by soriac** [soriac/tacs-no-se-cae-mas#7]
Como usuario poder definir un filtro de búsqueda sobre repos de github, al menos tiene que tener 5 criterios.

**Comment by thehighestprimenumber** [comment]
Podriamo usar la misma data del GET 

* - Nro de forks
* - Issues abiertos
* - Cantidad de estrellas
* - Lenguaje que utiliza

tambien podemos agregar cantidad de colaboradores, antiguedad...
